from .config import DEFAULT_DATA_CONFIG, DEFAULT_MATRIX_CONFIG, build_baseline_params, build_matrix_datasets
from .engine import (
    MatrixSearchArtifacts,
    build_parameter_grid,
    build_parameter_signature,
    filter_consistent_winners,
    find_intersection_winners,
    load_data,
    run_backtest,
    run_dataset_search,
    run_filter_matrix_search,
    run_out_of_sample_validation,
    split_in_sample_out_of_sample,
)
from .reporting import (
    print_consistency_report,
    print_dataset_summary,
    print_intersection_report,
    print_master_winners_report,
    print_matrix_plan,
    print_out_of_sample_report,
)

__all__ = [
    "DEFAULT_DATA_CONFIG",
    "DEFAULT_MATRIX_CONFIG",
    "build_baseline_params",
    "build_matrix_datasets",
    "MatrixSearchArtifacts",
    "build_parameter_grid",
    "build_parameter_signature",
    "filter_consistent_winners",
    "find_intersection_winners",
    "load_data",
    "run_backtest",
    "run_dataset_search",
    "run_filter_matrix_search",
    "run_out_of_sample_validation",
    "split_in_sample_out_of_sample",
    "print_consistency_report",
    "print_dataset_summary",
    "print_intersection_report",
    "print_master_winners_report",
    "print_matrix_plan",
    "print_out_of_sample_report",
]