RUN_NAME="XLM_1h"
AUTO_RESTART="yes"
RESTART_DELAY="10"
MAX_RESTARTS="0"
COMMAND_B64="Y2QgIi9Vc2Vycy9naWdpL0RvY3VtZW50cy8gcHl0aG9uX2xvY2FsL3BpbmVfYW5kX2JhY2h0ZXN0aW5nX3B5IiAmJiBzb3VyY2UgIi9Vc2Vycy9naWdpL0RvY3VtZW50cy8gcHl0aG9uX2xvY2FsL3BpbmVfYW5kX2JhY2h0ZXN0aW5nX3B5Ly52ZW52L2Jpbi9hY3RpdmF0ZSIgJiYgc2V0IC1hICYmIHNvdXJjZSAiL1VzZXJzL2dpZ2kvRG9jdW1lbnRzLyBweXRob25fbG9jYWwvcGluZV9hbmRfYmFjaHRlc3RpbmdfcHkvYmVhcl9zdHJhdGVneS9saXZlL2NvbnRyb2wvcHJvZmlsZXMvWExNXzFoLmVudiIgJiYgc2V0ICthICYmIHB5dGhvbiAtbSBiZWFyX3N0cmF0ZWd5LmxpdmUuYmVhcl9saXZlX3J1bm5lcg=="
UPDATED_AT="2026-05-22 10:20:40 UTC"
