"""Bear Strategy — sweep configuration base types.

Defines ``SweepConfig`` and ``SweepCombo``.

Do NOT edit this file to configure a sweep.  Instead create (or edit) a named
config file in this directory and run it with:

    python -m bear_strategy.backtest.vectorbt.sweep_run --config <name>

Available configs (filenames without .py):
    is_broad              — in-sample, broad SL/TP grid, fixed-TP exit   (default)
    oos_broad             — out-of-sample, same SL/TP grid
    rsi_exit_sweep        — sweep daily RSI exit modes alongside a narrow SL/TP grid
    macd_exit_sweep       — 1h MACD histogram cross-zero exit
    rsi_oversold_sweep    — 1h RSI oversold exit with level sweep
    ema_exit_sweep        — 1h EMA reclaim exit with period sweep
    funding_exit_sweep    — 8h funding regime-shift exit

Each named config imports ``build_config()`` from ``default.py`` and only
overrides the fields it needs to change.  Everything else stays as the shared
baseline.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from bear_strategy.backtest.vectorbt.configs.default import VbtRunConfig, build_config


# ─────────────────────────────────────────────────────────────────────────────
# SweepCombo — one fully-specified parameter point
# ─────────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class SweepCombo:
    """All the values that vary between iterations of a sweep.

    Everything else (pairs, dates, fees, regime params …) comes from
    ``SweepConfig.base``.

    Attributes
    ----------
    sl_mult:
        Stop-loss ATR multiple for this iteration.
    tp_mult:
        Take-profit ATR multiple for this iteration.
    exit_mode:
        Exit rule.  One of:
        ``"fixed_tp"``                  — close at TP hit (SL always active)
        ``"rsi_cross_up"``              — close when daily RSI crosses above level
        ``"fixed_tp_or_rsi_cross_up"``  — whichever fires first
        ``"macd_hist_cross_zero"``      — 1h MACD histogram negative→≥0
        ``"rsi_oversold"``              — 1h RSI drops below rsi_oversold_level
        ``"ema_reclaim"``               — 1h close crosses above EMA
        ``"funding_regime_shift"``      — smoothed funding drops ≤ threshold
    exit_rsi_level:
        Daily RSI threshold (rsi_cross_up modes). ``None`` for other modes.
    rsi_oversold_level:
        1h RSI oversold threshold (rsi_oversold mode). ``None`` for other modes.
    exit_ema_period:
        EMA period for ema_reclaim mode. ``None`` for other modes.
    """

    sl_mult:             float
    tp_mult:             float
    exit_mode:           str              = "fixed_tp"
    exit_rsi_level:      float | None     = None   # rsi_cross_up modes
    rsi_oversold_level:  float | None     = None   # rsi_oversold mode
    exit_ema_period:     int   | None     = None   # ema_reclaim mode


# ─────────────────────────────────────────────────────────────────────────────
# SweepConfig — what to vary and what to keep fixed
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class SweepConfig:
    """Full sweep configuration.

    ``base`` holds every fixed setting (pairs, dates, fees, regime params …).
    The fields below control the dimensions that are swept.

    Edit a named config file (e.g. ``is_broad.py``) — not this class — to
    configure a sweep.

    Attributes
    ----------
    base:
        VbtRunConfig providing all non-swept settings.
    sl_mults:
        ATR multiples to test for the stop-loss.
    tp_mults:
        ATR multiples to test for the take-profit.  Only pairs where
        ``tp_mult > sl_mult`` make it into the grid.
    exit_modes:
        Exit modes to sweep.
    exit_rsi_levels:
        Daily RSI thresholds — injected when mode contains ``"rsi_cross_up"``.
    rsi_oversold_levels:
        1h RSI oversold thresholds — injected when mode is ``"rsi_oversold"``.
    exit_ema_periods:
        EMA periods — injected when mode is ``"ema_reclaim"``.
    min_trades:
        Combos with fewer total trades (summed across all pairs) are excluded
        from analysis pivot tables.
    """

    base:                VbtRunConfig      = field(default_factory=build_config)
    sl_mults:            tuple[float, ...] = (1.0, 1.5, 2.0, 2.5, 3.0)
    tp_mults:            tuple[float, ...] = (1.5, 2.0, 3.0, 4.0, 5.0, 6.0)
    exit_modes:          tuple[str, ...]   = ("fixed_tp",)
    exit_rsi_levels:     tuple[float, ...] = (50.0,)
    rsi_oversold_levels: tuple[float, ...] = (30.0,)
    exit_ema_periods:    tuple[int, ...]   = (21,)
    min_trades:          int               = 10

    def combinations(self) -> list[SweepCombo]:
        """Return all valid (sl, tp, exit_mode [, mode-specific param]) combos.

        Rules:
        - ``tp_mult`` must exceed ``sl_mult`` (inverted R:R is excluded).
        - Mode-specific params are only injected for their respective modes.
        """
        combos: list[SweepCombo] = []
        for sl in self.sl_mults:
            for tp in self.tp_mults:
                if tp <= sl:
                    continue
                for mode in self.exit_modes:
                    if "rsi_cross_up" in mode:
                        for level in self.exit_rsi_levels:
                            combos.append(SweepCombo(sl, tp, mode, exit_rsi_level=level))
                    elif mode == "rsi_oversold":
                        for level in self.rsi_oversold_levels:
                            combos.append(SweepCombo(sl, tp, mode, rsi_oversold_level=level))
                    elif mode == "ema_reclaim":
                        for period in self.exit_ema_periods:
                            combos.append(SweepCombo(sl, tp, mode, exit_ema_period=period))
                    else:
                        # fixed_tp, macd_hist_cross_zero, funding_regime_shift:
                        # no extra dimension
                        combos.append(SweepCombo(sl, tp, mode))
        return combos


# ─────────────────────────────────────────────────────────────────────────────
# Backward-compatible alias
# Code that still imports SLTPSweepConfig or calls build_sweep_config() from
# this module continues to work unchanged.
# ─────────────────────────────────────────────────────────────────────────────

SLTPSweepConfig = SweepConfig


def build_sweep_config() -> SweepConfig:
    """Legacy default — delegates to the ``is_broad`` named config."""
    from bear_strategy.backtest.vectorbt.configs import load_sweep_config  # noqa: PLC0415
    return load_sweep_config("is_broad")
